title: Aliaskit Documentation
description: A comprehensive, modular open-source Bash alias toolkit designed for all Linux environments.
theme: jekyll-theme-cayman
url: "https://blackstart-labs.github.io"
baseurl: "/aliaskit"

include:
  - "docs"
  - "README.md"
  - "install.sh"
  - "uninstall.sh"
  
exclude:
  - "modules"
  - "core"
  - "config"
  - "update.sh"
  - ".github"
  - "Notes.txt"
